import type { Audit, Issue } from '../services/api'

const SEVERITY_ORDER: Record<Issue['severity'], number> = {
  critical: 0,
  high: 1,
  medium: 2,
  low: 3,
}

export function categoryLabel(c: string) {
  if (c === 'aiVisibility') return 'AI Visibility'
  if (c === 'accessibility') return 'Accessibility'
  if (c === 'performance') return 'Performance'
  if (c === 'seo') return 'SEO'
  if (c === 'geo') return 'GEO'
  if (c === 'aeo') return 'AEO'
  if (c === 'technical') return 'Technical'
  return c
}

export function sortIssuesBySeverity(issues: Issue[]) {
  return [...issues].sort((a, b) => {
    const sev = SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity]
    if (sev !== 0) return sev
    return (b.scoreImpact || 0) - (a.scoreImpact || 0)
  })
}

function siteName(audit: Audit) {
  return audit.website?.hostname || audit.crawlSummary?.finalUrl || 'website'
}

function scoreLine(audit: Audit) {
  const s = audit.scores
  return [
    `Overall ${audit.overallScore ?? '—'}`,
    `SEO ${s?.seo ?? '—'}`,
    `Technical ${s?.technical ?? '—'}`,
    `Performance ${s?.performance ?? '—'}`,
    `GEO ${s?.geo ?? '—'}`,
    `AEO ${s?.aeo ?? '—'}`,
    `AI Visibility ${s?.aiVisibility ?? '—'}`,
    `Accessibility ${s?.accessibility ?? '—'}`,
  ].join(' · ')
}

export function buildMarkdownReport(audit: Audit, issues: Issue[]) {
  const queued = sortIssuesBySeverity(issues)
  const host = siteName(audit)
  const date = new Date(audit.createdAt).toLocaleString()
  const counts = audit.issueCount

  const lines: string[] = [
    `# SiteLens audit — ${host}`,
    '',
    `Generated ${date}`,
    audit.crawlSummary?.finalUrl ? `URL: ${audit.crawlSummary.finalUrl}` : '',
    audit.crawlSummary?.pagesCrawled != null
      ? `Pages crawled: ${audit.crawlSummary.pagesCrawled}`
      : '',
    '',
    '## Scores',
    '',
    scoreLine(audit),
    '',
  ]

  if (counts) {
    lines.push(
      '## Issue counts',
      '',
      `- Critical: ${counts.critical}`,
      `- High: ${counts.high}`,
      `- Medium: ${counts.medium}`,
      `- Low: ${counts.low}`,
      '',
    )
  }

  lines.push(
    '## Fix queue',
    '',
    'Work **top to bottom**. Critical items first. Paste each prompt into Cursor, Claude Code, Codex, or Gemini CLI.',
    '',
  )

  queued.forEach((issue, idx) => {
    lines.push(
      `### ${idx + 1}. [${issue.severity.toUpperCase()} / ${categoryLabel(issue.category)}] ${issue.title}`,
      '',
      `**Why it matters:** ${issue.whyItMatters}`,
      '',
      `**Evidence:** ${issue.evidence}`,
      '',
      `**Fix:** ${issue.recommendation}`,
      '',
    )
    if (issue.fixPrompt) {
      lines.push('**AI prompt:**', '', '```', issue.fixPrompt.trim(), '```', '')
    }
  })

  if (queued.length === 0) {
    lines.push('_No issues found._', '')
  }

  lines.push('---', '', '_Report generated by SiteLens. Read-only audit — you choose what to apply._', '')
  return lines.filter((line, i, arr) => !(line === '' && arr[i - 1] === '')).join('\n')
}

export function buildFixQueueClipboard(audit: Audit, issues: Issue[]) {
  const queued = sortIssuesBySeverity(issues).filter((i) => i.fixPrompt)
  const host = siteName(audit)
  if (queued.length === 0) return ''

  const parts = [
    `# SiteLens fix queue — ${host}`,
    `Do these in order (${queued.length} prompts). Critical first. Paste one prompt at a time into your AI coding agent.`,
    '',
  ]

  queued.forEach((issue, idx) => {
    parts.push(
      `## ${idx + 1}. [${issue.severity.toUpperCase()} / ${categoryLabel(issue.category)}] ${issue.title}`,
      '',
      issue.fixPrompt!.trim(),
      '',
      '---',
      '',
    )
  })

  return parts.join('\n').replace(/\n---\n\n$/, '\n')
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

export function buildPrintableHtml(audit: Audit, issues: Issue[]) {
  const queued = sortIssuesBySeverity(issues)
  const host = escapeHtml(siteName(audit))
  const date = escapeHtml(new Date(audit.createdAt).toLocaleString())
  const url = escapeHtml(audit.crawlSummary?.finalUrl || audit.website?.url || '')
  const counts = audit.issueCount
  const s = audit.scores

  const scoreCells = [
    ['Overall', audit.overallScore],
    ['SEO', s?.seo],
    ['Technical', s?.technical],
    ['Perf', s?.performance],
    ['GEO', s?.geo],
    ['AEO', s?.aeo],
    ['AI Vis', s?.aiVisibility],
    ['A11y', s?.accessibility],
  ]
    .map(
      ([label, value]) =>
        `<div class="score"><span>${label}</span><strong>${value ?? '—'}</strong></div>`,
    )
    .join('')

  const issueHtml = queued
    .map((issue, idx) => {
      const prompt = issue.fixPrompt
        ? `<pre>${escapeHtml(issue.fixPrompt.trim())}</pre>`
        : ''
      return `<article>
        <h3>${idx + 1}. <span class="sev ${issue.severity}">${issue.severity}</span> ${escapeHtml(categoryLabel(issue.category))} — ${escapeHtml(issue.title)}</h3>
        <p><strong>Why it matters.</strong> ${escapeHtml(issue.whyItMatters)}</p>
        <p><strong>Evidence.</strong> ${escapeHtml(issue.evidence)}</p>
        <p><strong>Fix.</strong> ${escapeHtml(issue.recommendation)}</p>
        ${prompt}
      </article>`
    })
    .join('')

  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>SiteLens audit — ${host}</title>
  <style>
    body { font-family: Segoe UI, system-ui, sans-serif; color: #0b1220; max-width: 820px; margin: 32px auto; padding: 0 24px 64px; }
    h1 { font-size: 28px; margin: 0 0 4px; }
    .meta { color: #64748b; font-size: 13px; margin-bottom: 24px; }
    .scores { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin: 16px 0 28px; }
    .score { border: 1px solid #e2e8f0; border-radius: 10px; padding: 10px 12px; }
    .score span { display: block; font-size: 11px; text-transform: uppercase; letter-spacing: .08em; color: #64748b; }
    .score strong { font-size: 22px; }
    .counts { font-size: 13px; color: #334155; margin-bottom: 28px; }
    article { border-top: 1px solid #e2e8f0; padding: 18px 0; page-break-inside: avoid; }
    h3 { font-size: 16px; margin: 0 0 10px; }
    .sev { text-transform: uppercase; font-size: 11px; padding: 2px 6px; border-radius: 4px; margin-right: 6px; }
    .critical { background: #fee2e2; color: #b91c1c; }
    .high { background: #ffedd5; color: #c2410c; }
    .medium { background: #e0f2fe; color: #0369a1; }
    .low { background: #f1f5f9; color: #475569; }
    pre { background: #0b1220; color: #5eead4; padding: 12px; border-radius: 8px; white-space: pre-wrap; font-size: 11px; }
    footer { margin-top: 32px; font-size: 12px; color: #94a3b8; }
    @media print { body { margin: 0; } }
  </style>
</head>
<body>
  <h1>SiteLens audit — ${host}</h1>
  <p class="meta">${date}${url ? ` · ${url}` : ''}${audit.crawlSummary?.pagesCrawled != null ? ` · ${audit.crawlSummary.pagesCrawled} pages crawled` : ''}</p>
  <div class="scores">${scoreCells}</div>
  ${
    counts
      ? `<p class="counts">${counts.critical} critical · ${counts.high} high · ${counts.medium} medium · ${counts.low} low</p>`
      : ''
  }
  <h2>Fix queue (critical first)</h2>
  ${issueHtml || '<p>No issues found.</p>'}
  <footer>Generated by SiteLens. Read-only audit — you choose what to apply.</footer>
  <script>window.onload = function () { window.print(); }</script>
</body>
</html>`
}

function downloadBlob(filename: string, contents: string, type: string) {
  const blob = new Blob([contents], { type })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export function downloadMarkdownReport(audit: Audit, issues: Issue[]) {
  const host = siteName(audit).replace(/[^\w.-]+/g, '-')
  downloadBlob(`sitelens-${host}.md`, buildMarkdownReport(audit, issues), 'text/markdown;charset=utf-8')
}

export function printPdfReport(audit: Audit, issues: Issue[]) {
  const html = buildPrintableHtml(audit, issues)
  const popup = window.open('', '_blank', 'noopener,noreferrer,width=900,height=700')
  if (!popup) {
    downloadBlob(
      `sitelens-${siteName(audit).replace(/[^\w.-]+/g, '-')}.html`,
      html,
      'text/html;charset=utf-8',
    )
    return
  }
  popup.document.open()
  popup.document.write(html)
  popup.document.close()
}
